[workspace]
resolver = "2"
members = [
    "challenges/chal2",
    "challenges/interview",
    "cryptosystems",
    "snarks",
    "algebra",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
lambdaworks-crypto = "0.7.0"
lambdaworks-math = "0.7.0"

rand = "0.8.5"
rand_chacha = "0.3.1"
