[package]
name = "lambda-0b10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-crypto = "0.7.0"
lambdaworks-math = "0.7.0"
num-bigint = "0.4.5"
num-traits = "0.2.19"
rand = "0.8.5"
